name: exampleproject
description: A sample command-line application.
version: 1.0.0
publish_to: none

# homepage: https://www.example.com

environment:
  sdk: '>=2.15.1 <3.0.0'


dependencies:
    guru_cli:
       path: ../
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
